{{- if and .Values.rbac.create .Values.rbac.roles.viewer }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: casbin-rule-viewer-role
  labels:
    {{- include "casbin-kube.labels" . | nindent 4 }}
    {{- if .Values.rbac.aggregateTo.view }}
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    {{- end }}
rules:
  - apiGroups: ["casbin.grepplabs.com"]
    resources: ["rules"]
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["casbin.grepplabs.com"]
    resources: ["rules/status"]
    verbs:
      - get
{{- end }}
